### ISSUE TITLE
Handle error states

### ISSUE THREAD

**Issue by nikeshnazareth** [two-brothers/dosomething-app#1]
When Firebase authentication fails the app looks blank.
It should display an error message.

There are probably other error states that should be handled too

**Comment by nikeshnazareth** [comment]
I've made an example error widget that responds to the errorBloc. We should style that widget properly.

Also, we should go through the code base and raise errors wherever appropriate.

**Comment by bigfriedicecream** [comment]
We're now catching errors for the firebase calls. However, we are unable to produce any errors, so this is untested.
