### ISSUE TITLE
Search by calendar from home page

### ISSUE THREAD

**Issue by bigfriedicecream** [two-brothers/dosomething-app#11]

**Comment by nikeshnazareth** [comment]
I created a CalendarSelector widget based on https://pub.dev/packages/flutter_calendar_carousel. It correctly selects a date and loads the thing list.

Some things to fix:
- The rendering code complains about overflowing the available space, so I hardcoded the height/width. That should probably be expandable.
- It's on the front page (not loaded as a modal when the user tries to open it)
- The design is just the default - we should make it consistent with the rest of the app. I think that's Jarryd's problem to come up with a design.

**Comment by bigfriedicecream** [comment]
The calendar widget is currently hardcoded to `height: 350, width: 300`.
Most devices should be able to display this widget without overflow.
We are intentionally not fixing this issue.
