### ISSUE TITLE
Figure out location workflow

### ISSUE THREAD

**Issue by nikeshnazareth** [two-brothers/dosomething-app#29]
We can query the device to find out:
- if we have permissions to read the location
- if the location services are on
- the current location / last known location (assuming we have permissions)

We should figure out the workflow for each scenario / what happens to the drop-down menu if we are denied

**Comment by nikeshnazareth** [comment]
For reasons I don't understand, `Geolocator().checkGeolocationPermissionStatus()` returns `granted` even when the location services is disabled.

Check out this library: https://pub.dev/packages/location

Plan A: replace the `geolocator` library with the `location` one.
Plan B: continue using `geolocator` but use the `location` library to check if the services are enabled

**Comment by bigfriedicecream** [comment]
Plan A worked. We have tested it with the location services enabled/disabled. We should also test it with permission enabled/disabled

**Comment by bigfriedicecream** [comment]
We tested the phone permissons on android and it seems to work
