### ISSUE TITLE
Add DB access control

### ISSUE THREAD

**Issue by nikeshnazareth** [two-brothers/dosomething-app#31]
Currently anyone can modify the database. We should decide who should have access and then set the rules appropriately.

**Comment by nikeshnazareth** [comment]
I believe this is done. I added the following firebase rules: 

>  rules_version = '2';
> service cloud.firestore {
>   match /databases/{database}/documents {
>     match /{document=**} {
>       allow read;
>       allow write: if request.auth.uid == '1eR74UtD3BWc6M8fo0v7PJNYRYN2';
>     }
>   }
> }

This restricts write access to our 2brothers.master@gmail.com account. To deploy we will need to:
1. Transfer the CMS account to Jarryd, and
2. Update the security rule to apply to his account

Alternatively, we could make him store the database in his own gmail account.

I will keep this issue open until the transfer is complete

**Comment by bigfriedicecream** [comment]
We have:
1. Transferred the CMS account to Jarryd
2. Updated the security rule to apply to his account
3. Created a Firebase DB under his account
