### ISSUE TITLE
Duplicate models open on rotation

### ISSUE THREAD

**Issue by bigfriedicecream** [two-brothers/dosomething-app#5]
1. Open the filter Modal
2. Rotate your device
Notice how a new filter modal opens above the current one. The screen will appear darker

**Comment by nikeshnazareth** [comment]
This looks like it will help: https://gist.github.com/felangel/75f1ca6fc954f3672daf7962577d56f5

**Comment by bigfriedicecream** [comment]
I re-rested this and I can't reproduce the issue. It may have been fixed when we fixed `Equatable` 🤷‍♂ . I've removed all instances of `isFilterModalVisible` from the state and it's currently working as expected on the `develop` branch. Closing this issue.
